-- 12_seed_module_06.sql
-- Seed content items for Module 6 (Problem Solving) into yb_content_items
-- Safe to re-run: uses ON CONFLICT DO UPDATE
--
-- Module 6 UUID: 00000000-0000-4000-8000-000000000006  (from 01_seed_modules.sql)
-- Content item UUIDs: 00000000-0000-4000-a000-000000060001 through ...060013

INSERT INTO yb_content_items (id, module_id, type, title, instructions, xp_value, companion_website_ref, schema)
VALUES

-- ch6_item_01: Psychoeducation — Why Problem Solving is Hard with ADHD
(
  '00000000-0000-4000-a000-000000060001',
  '00000000-0000-4000-8000-000000000006',
  'psychoeducation',
  'Why Problem Solving is Hard with ADHD',
  'Read through this before starting the exercises.',
  20,
  NULL,
  '{
    "content_blocks": [
      {
        "heading": "The ADHD Problem-Solving Challenge",
        "body": "People with ADHD have difficulty solving problems for many reasons. You may respond impulsively rather than thinking through a solution and its potential outcomes. You may worry about minor, immediate issues and lose sight of the whole picture — in other words, you ''can''t see the wood for the trees''. Past experience may lead you to focus on negative outcomes, because that is what you have come to expect."
      },
      {
        "heading": "What is a Problem?",
        "body": "A ''problem'' can be defined as any life situation or task that requires something to be changed or resolved. Problems may be explicit (for example, needing accommodation) or intrinsic (for example, feeling unattractive). Obstacles such as novelty, ambiguity, conflicts of interest, or lack of resources may prevent an immediate solution from being effective."
      },
      {
        "heading": "How Executive Function Affects Problem Solving",
        "body": "For individuals with ADHD, problem-solving abilities are often affected by executive functioning difficulties: difficulty organising and sequencing information, and difficulty inhibiting an impulsive response. Core cognitive impairments — such as deficits in response inhibition, working memory, and attention — hinder the ability to generate, evaluate, and carry out solutions."
      },
      {
        "heading": "What You Will Learn in This Module",
        "body": "You will learn a structured five-stage method for solving problems: (1) identifying and defining the problem, (2) generating solutions, (3) evaluating solutions, (4) implementing the chosen solution, and (5) evaluating success. By adopting this methodical approach, more optimal outcomes can be reached."
      }
    ],
    "clinician_notes": "Normalise problem-solving difficulty as a cognitive impairment, not a character flaw. Assess the client''s predominant executive functioning weakness (impulsivity vs inattention) to guide emphasis in later exercises."
  }'::jsonb
),

-- ch6_item_02: Psychoeducation — Coping Strategies in Adult ADHD
(
  '00000000-0000-4000-a000-000000060002',
  '00000000-0000-4000-8000-000000000006',
  'psychoeducation',
  'Coping Strategies in Adult ADHD',
  'Read through this to understand how your current coping style may be helping or hindering your problem solving.',
  20,
  NULL,
  '{
    "content_blocks": [
      {
        "heading": "Maladaptive Coping Patterns",
        "body": "Adults with ADHD have been shown to use maladaptive coping strategies such as confrontation, escape-avoidance, and less planned problem-solving than individuals without ADHD. Impairment in executive function may lead you to lack flexibility in accessing and using a repertoire of appropriate coping strategies."
      },
      {
        "heading": "Impulsive vs Avoidant Responses",
        "body": "Difficulties with impulse control may lead you to cope with problems by responding rapidly and without thinking — reacting aggressively or defensively. Alternatively, due to previous adverse experiences and attentional difficulties, you may respond to stress or problems by not acknowledging the problem or actively avoiding dealing with it."
      },
      {
        "heading": "Emotion-Focused vs Problem-Focused Coping",
        "body": "Emotion-focused coping is used when the aim is to manage the emotions generated by a situation (for example, a death in the family). Problem-solving is used as a coping strategy in situations that are perceived as changeable or controllable. A functional response to stress involves the ability to use both types of coping in the appropriate situations."
      },
      {
        "heading": "The Role of Social Support",
        "body": "Close, supportive relationships provide the opportunity to consult about problems, gain helpful advice, and learn from the experience of others. However, adults with ADHD may have fewer confiding relationships available, which reduces this important stress-buffer."
      }
    ],
    "clinician_notes": "Assess the client''s predominant coping style (impulsive/confrontive vs avoidant). Gender differences exist: females are more likely to use emotion-focused coping; males are more likely to use problem-focused coping. Paradoxically, these are the exact areas where each gender with ADHD needs the most help."
  }'::jsonb
),

-- ch6_item_03: Worksheet — Common Domains of Problems in ADHD (Table 6.1)
(
  '00000000-0000-4000-a000-000000060003',
  '00000000-0000-4000-8000-000000000006',
  'worksheet',
  'Common Domains of Problems in ADHD (Table 6.1)',
  'Below is a list of common problem areas for adults with ADHD. For each domain, rate how much it currently affects you. This helps identify which problems to work on first.',
  50,
  'Table 6.1',
  '{
    "fields": [
      {"id": "work", "label": "Work — underachievement, being passed over for promotion, not meeting targets", "type": "scale", "required": true, "scale_min": 0, "scale_max": 10, "scale_labels": {"0": "Not a problem", "5": "Moderate problem", "10": "Severe problem"}},
      {"id": "transport", "label": "Transport — missing trains/buses, being late, vehicle maintenance tasks", "type": "scale", "required": true, "scale_min": 0, "scale_max": 10, "scale_labels": {"0": "Not a problem", "5": "Moderate problem", "10": "Severe problem"}},
      {"id": "financial", "label": "Financial — debts from not paying bills on time, impulsive spending", "type": "scale", "required": true, "scale_min": 0, "scale_max": 10, "scale_labels": {"0": "Not a problem", "5": "Moderate problem", "10": "Severe problem"}},
      {"id": "lack_of_support", "label": "Lack of support — difficulty setting up childcare, not accessing appropriate benefits", "type": "scale", "required": true, "scale_min": 0, "scale_max": 10, "scale_labels": {"0": "Not a problem", "5": "Moderate problem", "10": "Severe problem"}},
      {"id": "household", "label": "Household chores — incomplete tasks, putting off cleaning and laundry", "type": "scale", "required": true, "scale_min": 0, "scale_max": 10, "scale_labels": {"0": "Not a problem", "5": "Moderate problem", "10": "Severe problem"}},
      {"id": "relationships", "label": "Relationships — difficulty making or maintaining relationships, argumentative with friends", "type": "scale", "required": true, "scale_min": 0, "scale_max": 10, "scale_labels": {"0": "Not a problem", "5": "Moderate problem", "10": "Severe problem"}},
      {"id": "self_esteem", "label": "Low self-esteem — feeling like a failure, expectancy of failure", "type": "scale", "required": true, "scale_min": 0, "scale_max": 10, "scale_labels": {"0": "Not a problem", "5": "Moderate problem", "10": "Severe problem"}},
      {"id": "sleep", "label": "Sleep — restlessness, insomnia, difficulty getting out of bed on time", "type": "scale", "required": true, "scale_min": 0, "scale_max": 10, "scale_labels": {"0": "Not a problem", "5": "Moderate problem", "10": "Severe problem"}},
      {"id": "disorganisation", "label": "Disorganisation — time-wasting traps, day lacking structure, poor work-leisure balance", "type": "scale", "required": true, "scale_min": 0, "scale_max": 10, "scale_labels": {"0": "Not a problem", "5": "Moderate problem", "10": "Severe problem"}},
      {"id": "substance_misuse", "label": "Substance misuse — drug or alcohol use as a maladaptive coping strategy", "type": "scale", "required": true, "scale_min": 0, "scale_max": 10, "scale_labels": {"0": "Not a problem", "5": "Moderate problem", "10": "Severe problem"}},
      {"id": "trouble_with_police", "label": "Trouble with police — opportunistic incidents, aggressive outbursts", "type": "scale", "required": true, "scale_min": 0, "scale_max": 10, "scale_labels": {"0": "Not a problem", "5": "Moderate problem", "10": "Severe problem"}},
      {"id": "top_three", "label": "Looking at your ratings, which 3 problem areas would you most like to work on?", "type": "textarea", "required": true, "placeholder": "List your top 3 problem areas and briefly explain why..."}
    ],
    "scoring": {"method": "none"},
    "instructions_for_patient": "Rate each area honestly. There is no judgement here — this helps you and your therapist decide where to focus.",
    "clinician_notes": "Use this as a problem inventory at the start of the module. The top-rated domains become the raw material for the problem-solving exercises that follow. Revisit at module end to track change."
  }'::jsonb
),

-- ch6_item_04: Exercise — Identifying and Defining the Problem (Exercise 6.1)
(
  '00000000-0000-4000-a000-000000060004',
  '00000000-0000-4000-8000-000000000006',
  'exercise',
  'Identifying and Defining the Problem (Exercise 6.1)',
  'Before you can solve a problem, you need to understand it clearly. Answer these four questions about a problem you are currently facing. These questions help determine whether the problem really needs tackling or whether it comes from a general attitude or anxious response-style.',
  70,
  'Exercise 6.1',
  '{
    "fields": [
      {"id": "problem_description", "label": "Briefly describe the problem you want to work on", "type": "textarea", "required": true, "placeholder": "e.g. I am unsure whether to tell my partner about my ADHD, I am always late for work..."},
      {"id": "q1_why_problem", "label": "1. Why is it a problem?", "type": "textarea", "required": true, "placeholder": "What makes this situation problematic for you specifically?"},
      {"id": "q2_how_affects", "label": "2. How does it affect you?", "type": "textarea", "required": true, "placeholder": "What impact does it have on your daily life, mood, relationships, work?"},
      {"id": "q3_potential_change", "label": "3. Does the situation have potential for change?", "type": "textarea", "required": true, "placeholder": "Is this something that could realistically be different? What would change look like?"},
      {"id": "q4_if_not_solved", "label": "4. What could happen if it is not solved?", "type": "textarea", "required": true, "placeholder": "What are the consequences of leaving this problem unresolved?"},
      {"id": "solvable_or_worry", "label": "Based on your answers, is this a solvable problem or more of a general worry/anxiety?", "type": "select", "required": true, "options": ["Solvable problem — I can take action", "General worry — I need to manage my feelings about it", "Partly both — some parts are solvable, some are not"]}
    ],
    "scoring": {"method": "none"},
    "instructions_for_patient": "Choose a real problem you are facing right now. It does not have to be the biggest problem in your life — start with something manageable.",
    "clinician_notes": "This is the gateway exercise for the module. If the client identifies the problem as a general worry rather than a solvable problem, redirect to emotion-focused coping (Chapters 9-11). Help the client distinguish between problems that require action and those that require emotional regulation."
  }'::jsonb
),

-- ch6_item_05: Worksheet — Understanding the Problem (Table 6.2)
(
  '00000000-0000-4000-a000-000000060005',
  '00000000-0000-4000-8000-000000000006',
  'worksheet',
  'Understanding the Problem (Table 6.2)',
  'Use this worksheet to break down up to four problems systematically. For each problem, answer the three questions. This helps make problems more clearly defined and easier to understand.',
  50,
  'Table 6.2',
  '{
    "fields": [
      {
        "id": "problems",
        "label": "Define your problems using the three-question framework",
        "type": "repeating_group",
        "required": true,
        "sub_fields": [
          {"id": "problem_name", "label": "Problem", "type": "text", "placeholder": "e.g. I am often late for work"},
          {"id": "what_is_problem", "label": "1. What is the problem or situation?", "type": "textarea", "placeholder": "Describe the specific situation..."},
          {"id": "what_do_i_want", "label": "2. What do I want?", "type": "textarea", "placeholder": "What would the ideal outcome look like?"},
          {"id": "what_are_obstacles", "label": "3. What are the obstacles to getting what I want?", "type": "textarea", "placeholder": "What is standing in the way?"}
        ],
        "min_items": 1,
        "max_items": 4
      }
    ],
    "scoring": {"method": "none"},
    "instructions_for_patient": "Start with 1-2 problems. You can add more later. The obstacles column is especially important — it reveals what you actually need to solve.",
    "clinician_notes": "This worksheet mirrors Table 6.2 from the YB Programme. Encourage the client to be specific — vague problems lead to vague solutions. If a client sets unrealistic goals in question 2, this may indicate the real problem is perfectionism or poor self-appraisal rather than the stated problem."
  }'::jsonb
),

-- ch6_item_06: Exercise — Brainstorming Solutions
(
  '00000000-0000-4000-a000-000000060006',
  '00000000-0000-4000-8000-000000000006',
  'exercise',
  'Brainstorming Solutions',
  'Now that you have defined your problem clearly, it is time to generate as many solutions as possible. The three rules of brainstorming are: (1) quantity leads to quality, (2) defer judgement — do not evaluate ideas yet, and (3) variety — include extreme, silly, and creative ideas alongside sensible ones.',
  70,
  'Figure 6.1',
  '{
    "fields": [
      {"id": "problem_statement", "label": "What problem are you brainstorming solutions for?", "type": "textarea", "required": true, "placeholder": "Write the specific problem you defined in the previous exercise..."},
      {
        "id": "solutions",
        "label": "List every possible solution — including extreme and ridiculous ones!",
        "type": "repeating_group",
        "required": true,
        "sub_fields": [
          {"id": "solution_idea", "label": "Solution idea", "type": "text", "placeholder": "Any idea at all — do not judge it yet"}
        ],
        "min_items": 6,
        "max_items": 15
      },
      {"id": "habitual_response", "label": "What is your usual habitual response to this kind of problem?", "type": "textarea", "required": true, "placeholder": "e.g. I usually avoid it, I storm out, I panic and do the first thing that comes to mind..."},
      {"id": "past_solutions", "label": "Think about similar problems in the past. What worked? What did not work?", "type": "textarea", "required": false, "placeholder": "Reviewing past experience helps — what helped, what made things worse, who was helpful?"}
    ],
    "scoring": {"method": "none"},
    "instructions_for_patient": "Do not filter your ideas. The sillier the better at this stage — it loosens up creative thinking and stops you from grabbing the first idea that comes to mind.",
    "clinician_notes": "This is a key exercise for impulsive clients who tend to lunge at the first solution. Ensure they generate at least 6 ideas before moving on. Identify maladaptive habitual responses (e.g. storming out, avoidance) collaboratively so the client can recognise them when they occur. Encourage reviewing past solutions — this is often overlooked by ADHD adults."
  }'::jsonb
),

-- ch6_item_07: Worksheet — Pros and Cons List (Table 6.3)
(
  '00000000-0000-4000-a000-000000060007',
  '00000000-0000-4000-8000-000000000006',
  'worksheet',
  'Pros and Cons List (Table 6.3)',
  'After eliminating the most unrealistic options from your brainstorm, you should be left with 2-3 realistic solutions. For each one, list the pros and cons, then rank the 5 most important issues to help you decide.',
  50,
  'Table 6.3',
  '{
    "fields": [
      {"id": "problem_statement", "label": "What problem are you evaluating solutions for?", "type": "textarea", "required": true},
      {
        "id": "solution_options",
        "label": "Evaluate your realistic solution options",
        "type": "repeating_group",
        "required": true,
        "sub_fields": [
          {"id": "solution_name", "label": "Solution option", "type": "text", "placeholder": "e.g. Tell her honestly and directly"},
          {"id": "pros", "label": "Pros (advantages of this solution)", "type": "textarea", "placeholder": "List all the advantages..."},
          {"id": "cons", "label": "Cons (disadvantages of this solution)", "type": "textarea", "placeholder": "List all the disadvantages..."}
        ],
        "min_items": 2,
        "max_items": 4
      },
      {"id": "top_five_issues", "label": "Rank the 5 most important issues from all your pros and cons lists (1 = most important)", "type": "textarea", "required": true, "placeholder": "1. ...\n2. ...\n3. ...\n4. ...\n5. ..."},
      {"id": "chosen_solution", "label": "Based on this analysis, which solution will you go with?", "type": "textarea", "required": true, "placeholder": "Which solution has the strongest case?"}
    ],
    "scoring": {"method": "none"},
    "instructions_for_patient": "Consider each option in terms of: likelihood of achieving the goal, emotional well-being, time and effort required. Weightings can be given based on how important each factor is to you.",
    "clinician_notes": "This is a structured decision-making exercise. If the client struggles to rank issues, help them assign importance weightings. Often the advantages of one solution are the disadvantages of another — point this out. The ranking usually makes the decision clearer."
  }'::jsonb
),

-- ch6_item_08: Exercise — Evaluating Effort and Motivation
(
  '00000000-0000-4000-a000-000000060008',
  '00000000-0000-4000-8000-000000000006',
  'exercise',
  'Evaluating Effort and Motivation',
  'People with ADHD may avoid adaptive problem-solving when the effort involved feels too great. A desire for immediate gratification can lead to choosing a short cut over a longer-term solution with greater reward. This exercise helps you examine your motivation to change.',
  70,
  NULL,
  '{
    "fields": [
      {"id": "chosen_solution", "label": "What solution have you chosen to implement?", "type": "textarea", "required": true},
      {"id": "effort_required", "label": "How much effort does this solution require? (1-10)", "type": "scale", "required": true, "scale_min": 1, "scale_max": 10, "scale_labels": {"1": "Very little effort", "5": "Moderate effort", "10": "Enormous effort"}},
      {"id": "short_cut_temptation", "label": "What is the ''short cut'' or avoidance option? (The easier thing you might do instead)", "type": "textarea", "required": true, "placeholder": "e.g. Just not tell her, keep putting it off, ignore the bills..."},
      {"id": "short_cut_consequences", "label": "What would happen long-term if you took the short cut?", "type": "textarea", "required": true, "placeholder": "Think about the consequences over weeks and months, not just today..."},
      {"id": "readiness_stage", "label": "Where are you on the readiness to change scale?", "type": "select", "required": true, "options": ["Precontemplation — I am not sure I want to change this", "Contemplation — I am thinking about it but still uncertain", "Preparation — I am getting ready to act", "Action — I am ready to do this now", "Maintenance — I have already started and want to keep going"]},
      {"id": "what_would_help", "label": "What would help you move to the next stage of readiness?", "type": "textarea", "required": false, "placeholder": "e.g. Support from a friend, more rehearsal, breaking it into smaller steps..."}
    ],
    "scoring": {"method": "none"},
    "instructions_for_patient": "Be honest about the temptation to take the easy way out. Recognising the short cut is the first step to resisting it.",
    "clinician_notes": "This exercise uses motivational interviewing principles and references the Stages of Change model (Prochaska & DiClemente, 1982). Challenge delaying tactics (''I will do it next week'') while recognising that in some cases delay may genuinely be strategic. The primary therapeutic task is helping the client learn to think before acting or reacting impulsively."
  }'::jsonb
),

-- ch6_item_09: Exercise — Rehearsal and Role-Play Preparation
(
  '00000000-0000-4000-a000-000000060009',
  '00000000-0000-4000-8000-000000000006',
  'exercise',
  'Rehearsal and Role-Play Preparation',
  'Rehearsal is an effective way of preparing for a difficult conversation or situation. This exercise guides you through two powerful techniques: imaginal rehearsal (visualising the scenario) and perspective-taking role-play (putting yourself in the other person''s shoes).',
  70,
  NULL,
  '{
    "fields": [
      {"id": "scenario_description", "label": "Describe the situation you need to prepare for", "type": "textarea", "required": true, "placeholder": "e.g. Telling my partner about ADHD, asking my boss for flexible hours, confronting a friend about money..."},
      {"id": "imaginal_setting", "label": "Imaginal rehearsal — Where and when will this happen? Describe the surroundings in detail.", "type": "textarea", "required": true, "placeholder": "e.g. At her house, in the kitchen over coffee, evening after dinner, quiet and relaxed..."},
      {"id": "what_will_you_say", "label": "What will you say? Write out your key points.", "type": "textarea", "required": true, "placeholder": "Write the main things you want to communicate..."},
      {"id": "how_did_you_feel", "label": "After rehearsing in your mind, how did you feel during the process?", "type": "textarea", "required": true, "placeholder": "Anxious? Confident? Distracted? Note any feelings that came up..."},
      {"id": "pitfalls_identified", "label": "What possible pitfalls did you notice during rehearsal?", "type": "textarea", "required": false, "placeholder": "e.g. I got distracted by the TV, I started to feel too anxious to continue, I forgot my key point..."},
      {"id": "other_persons_perspective", "label": "Perspective taking — Put yourself in the other person''s shoes. What might they be thinking or feeling? What questions might they ask?", "type": "textarea", "required": true, "placeholder": "Try to see the situation from their viewpoint..."},
      {"id": "adjustments", "label": "Based on the rehearsal and perspective-taking, what adjustments will you make to your plan?", "type": "textarea", "required": false, "placeholder": "e.g. Use more sensitive wording, have written information to hand, choose a quieter setting..."}
    ],
    "scoring": {"method": "none"},
    "instructions_for_patient": "Close your eyes and really imagine the scene in detail — the surroundings, what you will say, the other person''s reactions. Practising this way makes you feel less nervous when the situation actually happens.",
    "clinician_notes": "Guide the client into an imaginal mode by cueing sensory details (colours, sounds, smells). Establish a calm imaginal ''safe place'' first. If the client becomes distressed during imaginal work, use a predetermined signal (e.g. lifting a finger) to redirect to a neutral calm scene with breathing exercises. Reversed role-play (therapist plays the client, client plays the other person) is especially powerful for interpersonal problem solutions."
  }'::jsonb
),

-- ch6_item_10: Worksheet — Challenging Cognitive Distortions in Problem Solving
(
  '00000000-0000-4000-a000-000000060010',
  '00000000-0000-4000-8000-000000000006',
  'worksheet',
  'Challenging Cognitive Distortions in Problem Solving',
  'Distorted thinking can sabotage the problem-solving process. You may discard helpful solutions due to faulty thinking patterns. This worksheet helps you identify and challenge three common distortions that affect problem solving in ADHD.',
  50,
  NULL,
  '{
    "fields": [
      {"id": "problem_context", "label": "What problem or solution are you thinking about?", "type": "textarea", "required": true},
      {"id": "overgeneralisation", "label": "Overgeneralisation — Are you telling yourself ''everything always goes wrong, so why bother trying''? Write down the thought.", "type": "textarea", "required": false, "placeholder": "e.g. ''I always mess things up'', ''Nothing ever works out for me''..."},
      {"id": "overgeneralisation_challenge", "label": "Challenge: Can you think of a time when something DID go right? What actually happened?", "type": "textarea", "required": false, "placeholder": "Find evidence that contradicts the overgeneralisation..."},
      {"id": "black_and_white", "label": "Black-and-white thinking — Are you telling yourself ''if I can''t get it 100% right, there''s no point doing it at all''?", "type": "textarea", "required": false, "placeholder": "e.g. ''If I can''t solve this perfectly, I won''t bother'', ''It has to go exactly as planned or it''s a failure''..."},
      {"id": "black_and_white_challenge", "label": "Challenge: What would ''good enough'' look like? Is a partial success still better than no attempt?", "type": "textarea", "required": false, "placeholder": "Describe what a partial or imperfect success would look like..."},
      {"id": "jumping_to_conclusions", "label": "Jumping to conclusions — Are you predicting a negative outcome without evidence? Write down the thought.", "type": "textarea", "required": false, "placeholder": "e.g. ''I only managed Part 1, so I''ll never finish Part 4'', ''She''ll definitely react badly''..."},
      {"id": "jumping_challenge", "label": "Challenge: What is the actual evidence? Have you considered alternative explanations?", "type": "textarea", "required": false, "placeholder": "What other outcomes are possible? What evidence are you ignoring?"},
      {"id": "revised_thinking", "label": "After challenging these thoughts, write a more balanced view of your problem and solution.", "type": "textarea", "required": true, "placeholder": "Restate the situation with a more realistic, balanced perspective..."}
    ],
    "scoring": {"method": "none"},
    "instructions_for_patient": "You do not need to fill in all three distortion types — just the ones that apply to you. The important thing is to spot the pattern and challenge it.",
    "clinician_notes": "This exercise is based on cognitive restructuring principles. Common in ADHD: jumping to conclusions (especially based on one past negative experience) and overgeneralisation. Help the client identify evidence they may be ignoring — e.g. friends who reacted positively, partial successes they discount. For deeper cognitive distortion work, refer to Chapter 11 (Low Mood and Depression)."
  }'::jsonb
),

-- ch6_item_11: Exercise — Implementing the Chosen Solution — Action Plan
(
  '00000000-0000-4000-a000-000000060011',
  '00000000-0000-4000-8000-000000000006',
  'exercise',
  'Implementing the Chosen Solution — Action Plan',
  'You have identified your problem, generated solutions, evaluated them, and chosen the best one. Now it is time to plan the implementation. Break your solution into small, concrete steps to avoid procrastination and time-wasting traps.',
  70,
  NULL,
  '{
    "fields": [
      {"id": "chosen_solution", "label": "What solution are you implementing?", "type": "textarea", "required": true},
      {
        "id": "action_steps",
        "label": "Break this down into small, achievable steps",
        "type": "repeating_group",
        "required": true,
        "sub_fields": [
          {"id": "step_description", "label": "Step", "type": "text", "placeholder": "One specific, concrete action"},
          {"id": "when", "label": "When will you do this?", "type": "text", "placeholder": "Specific day and time"},
          {"id": "done", "label": "Done?", "type": "select", "options": ["Not yet", "Done", "Partially done", "Skipped"]}
        ],
        "min_items": 2,
        "max_items": 10
      },
      {"id": "best_time_and_place", "label": "What is the best time and situation to carry out the main action? Can you ''set the scene''?", "type": "textarea", "required": true, "placeholder": "Think about when you are at your best, who needs to be present, what setting is ideal..."},
      {"id": "potential_obstacles", "label": "What could go wrong? What might derail your plan?", "type": "textarea", "required": false, "placeholder": "Distractions, forgetting, anxiety, other people''s reactions..."},
      {"id": "obstacle_plan", "label": "How will you deal with those obstacles if they arise?", "type": "textarea", "required": false, "placeholder": "Have a backup plan for each obstacle..."}
    ],
    "scoring": {"method": "none"},
    "instructions_for_patient": "Be as specific as possible with your steps and timings. Vague plans lead to procrastination. Come back to mark each step as done.",
    "clinician_notes": "Emphasise breaking the goal into small achievable steps — this is where working memory difficulties derail ADHD adults (they miss crucial components or muddle sequences). If the problem involves interpersonal relationships, help the client think about setting the scene. Review progress in the following session."
  }'::jsonb
),

-- ch6_item_12: Diary — Problem-Solving Success Evaluation Diary
(
  '00000000-0000-4000-a000-000000060012',
  '00000000-0000-4000-8000-000000000006',
  'diary',
  'Problem-Solving Success Evaluation Diary',
  'After implementing your solution, use this diary to evaluate how it went. Evaluating success is a crucial step that provides a constructive feedback loop for future problem solving. Remember: partial success still counts!',
  60,
  NULL,
  '{
    "fields": [
      {"id": "date", "label": "Date", "type": "date", "required": true},
      {"id": "problem_solved", "label": "What problem did you work on?", "type": "textarea", "required": true},
      {"id": "solution_implemented", "label": "What solution did you implement?", "type": "textarea", "required": true},
      {"id": "outcome", "label": "What happened? Did you achieve the desired result?", "type": "select", "required": true, "options": ["Full success", "Partial success", "No success — but I tried", "I could not attempt it"]},
      {"id": "outcome_details", "label": "Describe what happened in detail", "type": "textarea", "required": true, "placeholder": "What went well? What was unexpected? How did the other person react?"},
      {"id": "feelings_about_outcome", "label": "How do you feel about the outcome?", "type": "textarea", "required": true, "placeholder": "Proud? Relieved? Disappointed? What has this done for your confidence?"},
      {"id": "what_would_you_change", "label": "If you could do it again, what would you change?", "type": "textarea", "required": false, "placeholder": "Any adjustments for next time?"},
      {"id": "reward", "label": "How will you reward yourself for attempting and/or succeeding?", "type": "textarea", "required": true, "placeholder": "Rewards are crucial! Plan something nice for yourself — you earned it."},
      {"id": "impact_on_original_problem", "label": "Looking back at the original problem — was it as life-threatening as you first thought?", "type": "textarea", "required": false, "placeholder": "Often problems feel smaller once we have faced them..."}
    ],
    "scoring": {"method": "none"},
    "instructions_for_patient": "Fill this in as soon as possible after you implement your solution. Celebrate your achievements, no matter how small. Rewards are crucial to build motivation for future problem solving.",
    "clinician_notes": "Provide strong positive feedback — it is a powerful reward and increases likelihood of future problem-solving engagement. In case of partial or no success, systematically evaluate obstacles and recommence the five-stage process. Explore feelings about successful resolution (fear of consequences, anxiety about change). Ensure the client sets up a reward — this is often forgotten but critical for ADHD motivation."
  }'::jsonb
),

-- ch6_item_13: Psychoeducation — Positive Reappraisal — Your ADHD Strength
(
  '00000000-0000-4000-a000-000000060013',
  '00000000-0000-4000-8000-000000000006',
  'psychoeducation',
  'Positive Reappraisal — Your ADHD Strength',
  'Read through this final section to learn about a surprising strength that many adults with ADHD possess.',
  20,
  NULL,
  '{
    "content_blocks": [
      {
        "heading": "The Resilience Factor",
        "body": "Despite the many pitfalls experienced by adults with ADHD in solving problems, research shows that people with ADHD often reappraise stressful situations in a positive way. This means you may be more resilient to disappointments and better able to ''bounce back'' from difficulties."
      },
      {
        "heading": "Impulsivity as a Strength",
        "body": "This positive reappraisal trait has been found to be positively associated with impulsivity. More impulsive individuals may be less prone to dwell on their difficulties and attempt to get on with life. This can be hugely advantageous and may underpin many ADHD individuals'' creative and entrepreneurial personality characteristics and successes."
      },
      {
        "heading": "Building on Your Strengths",
        "body": "The goal of this module is not to eliminate your natural tendencies, but to add a structured method alongside them. Your ability to bounce back, combined with a methodical problem-solving approach, is a powerful combination."
      }
    ],
    "clinician_notes": "End the module on a positive note. Reframe the impulsivity that causes problem-solving difficulty as also being a source of resilience and positive reappraisal. This helps with self-esteem and motivation."
  }'::jsonb
)

ON CONFLICT (id) DO UPDATE SET
  module_id              = EXCLUDED.module_id,
  type                   = EXCLUDED.type,
  title                  = EXCLUDED.title,
  instructions           = EXCLUDED.instructions,
  xp_value               = EXCLUDED.xp_value,
  companion_website_ref  = EXCLUDED.companion_website_ref,
  schema                 = EXCLUDED.schema,
  updated_at             = now();
